-- Newsletter Issue #3 — 2026-03-22
-- Run this against your Neon database to add the new issue.
-- NOTE: Run add_sort_order_to_big_story.sql first if you haven't already.

WITH new_newsletter AS (
  INSERT INTO newsletters (title, subtitle, issue_date)
  VALUES (
    'Prompt Notes - Issue #3',
    '',
    '2026-03-22'
  )
  RETURNING id
),

big1 AS (
  INSERT INTO big_story (newsletter_id, title, description, body, link, badge, badge_class, sort_order)
  SELECT
    id,
    'From Cloud APIs to Agent PCs: Why GTC 2026 is the End of the "Token Tax"',
    'NVIDIA''s GTC 2026 marked a pivotal shift: the tools to build production-grade AI systems—RAG pipelines, autonomous agents, and custom fine-tuned models—are now available entirely on local RTX hardware.',
    '• Cost & Privacy Sovereignty: With the release of NemoClaw and the Nemotron 3 family (specifically the 120B Super and 4B Nano), you can now build production-grade RAG systems and autonomous agents that run entirely on local RTX hardware. This removes the "token tax" and allows for the processing of sensitive data without it ever leaving the device.• Infrastructure Optimization: The introduction of NVFP4 and FP8 distilled models means you can achieve a 2.1x performance boost on local video and image generation. This allows for high-throughput creative workflows on a single workstation that previously required data-center-grade clusters.• Rapid Fine-Tuning: The launch of Unsloth Studio provides a graph-based UI that simplifies the fine-tuning of over 500 models. It reduces VRAM usage by 70%, enabling you to customize high-parameter models on consumer GPUs—essential for building niche assistants like a "Podcast Researcher."',
    'https://blogs.nvidia.com/blog/rtx-ai-garage-gtc-2026-nemoclaw/',
    'NVIDIA',
    'green',
    1
  FROM new_newsletter
),

big2 AS (
  INSERT INTO big_story (newsletter_id, title, description, body, link, badge, badge_class, sort_order)
  SELECT
    id,
    'Beyond Wireframes: How Google Stitch is Automating the Design-to-Code Pipeline',
    'Google Stitch redefines how engineers think about UI generation—moving beyond static mockups to a system where design rules are expressed as agent-readable markdown and entire user journeys are auto-generated.',
    '• Design-as-Code (DESIGN.md): Google introduced a markdown-based design system (DESIGN.md). This allows you to import/export design rules as agent-friendly files, making it easier to programmatically apply consistent UI across different projects or AI-generated applications.• Automated User Journeys: Stitch can "stitch" screens together and predict logical next steps. For engineers building automated workflows, this provides a visual debugging layer where you can preview interactive app flows generated by AI in real-time.• Seamless Integration (MCP & SDK): With the new Stitch MCP (Model Context Protocol) server, you can leverage Stitch''s design capabilities directly within your own developer tools and skills. This enables a more synchronized workflow between the AI, the design agent, and your deployment environment (like AI Studio).',
    'https://blog.google/innovation-and-ai/models-and-research/google-labs/stitch-ai-ui-design/',
    'Google',
    'blue',
    2
  FROM new_newsletter
)

SELECT 'Done' as status;
