-- Newsletter Issue #2 — 2026-03-06
-- Run this against your Neon database to add the new issue.

WITH new_newsletter AS (
  INSERT INTO newsletters (title, subtitle, issue_date)
  VALUES (
    'Prompt Notes - Issue #1',
    '',
    '2026-03-06'
  )
  RETURNING id
),

big AS (
  INSERT INTO big_story (newsletter_id, title, description, body, link, badge, badge_class)
  SELECT
    id,
    'Introducing GPT-5.4 and the Thinking System Card',
    'OpenAI has officially launched GPT-5.4 alongside its new Thinking System Card, showcasing major advancements in frontier model logic. The release specifically highlights how these reasoning models generate complex chains of thought, offering a deeper look into their internal problem-solving mechanics.',
    'AI engineers can leverage these exposed reasoning traces to better understand, debug, and steer complex multi-step logic generated by the model.',
    'https://openai.com/news',
    'OpenAI',
    'green'
  FROM new_newsletter
),

eng AS (
  INSERT INTO github_repos (newsletter_id, name, description, link)
  SELECT
    id,
    'Modular Diffusers',
    'Hugging Face introduces Modular Diffusers — composable building blocks to customize generative diffusion pipelines. By breaking down monolithic architectures, developers can dynamically swap components like schedulers for enhanced control in image generation tasks. Decomposing diffusion models into modular pipelines allows engineers to seamlessly interchange specific attention mechanisms without rewriting the entire generation stack.',
    'https://huggingface.co/blog/modular-diffusers'
  FROM new_newsletter
),

paper AS (
  INSERT INTO projects (newsletter_id, name, description, link)
  SELECT
    id,
    'Phi-4-reasoning-vision-15B Technical Report',
    'Details the architecture and training methodology behind Phi-4-reasoning-vision-15B — a new multimodal model focused on advanced visual reasoning. It achieves strong spatial and logical capabilities in a compact 15B parameter footprint, enabling deployment on edge devices or cost-effective cloud instances.',
    'https://arxiv.org/abs/2603.03975'
  FROM new_newsletter
),

tool AS (
  INSERT INTO tools (newsletter_id, name, description, badge)
  SELECT
    id,
    'OpenSandbox',
    'A general-purpose execution platform by Alibaba for safely running AI applications and autonomous agents. Provides multi-language SDKs, unified APIs, and Docker/Kubernetes runtimes — ideal for letting coding agents compile and test generated code without risking host system integrity.',
    'Alibaba'
  FROM new_newsletter
),

ai AS (
  INSERT INTO ai_news (newsletter_id, title, description, badge, badge_class, link, sort_order)
  SELECT
    id,
    'Gemini 3.1 Flash-Lite',
    'Google DeepMind announces Gemini 3.1 Flash-Lite, an optimized infrastructure deployment designed for massive-scale intelligence operations. Focuses on maximizing inference throughput and minimizing latency — helping AI infrastructure teams significantly reduce inference costs for high-volume, real-time generative AI applications.',
    'Google DeepMind',
    'blue',
    'https://deepmind.google/news/',
    1
  FROM new_newsletter
)

INSERT INTO must_read (newsletter_id, title, description, why, link, badge, badge_class, sort_order)
SELECT
  id,
  'Can Coding Agents Become Engineers? We''re Finding Out.',
  'Scale AI Research introduces SWE-Atlas, an evaluation suite that tests coding agents not just on their final output, but on how effectively they investigate systems and gather evidence — just like a junior software engineer would.',
  NULL,
  'https://scale.com/blog/swe-atlas',
  'Scale AI',
  'purple',
  1
FROM new_newsletter;
