-- Newsletter Issue #2 — 2026-03-09
-- Run this against your Neon database to add the new issue.

WITH new_newsletter AS (
  INSERT INTO newsletters (title, subtitle, issue_date)
  VALUES (
    'Prompt Notes - Issue #1',
    '',
    '2026-03-09'
  )
  RETURNING id
),

big AS (
  INSERT INTO big_story (newsletter_id, title, description, body, link, badge, badge_class)
  SELECT
    id,
    'Introducing GPT-5.4 and the Thinking System Card',
    'OpenAI has officially launched GPT-5.4 alongside its new Thinking System Card, showcasing major advancements in frontier model logic. The release specifically highlights how these reasoning models generate complex chains of thought, offering a deeper look into their internal problem-solving mechanics.',
    'AI engineers can leverage these exposed reasoning traces to better understand, debug, and steer complex multi-step logic generated by the model.',
    'https://openai.com/news',
    'OpenAI',
    'green'
  FROM new_newsletter
),

paper AS (
  INSERT INTO research_papers (newsletter_id, name, description, link)
  SELECT
    id,
    'CoT Controllability',
    'Investigates whether AI models can hide or manipulate their chain-of-thought reasoning. Models can control their final answers but consistently fail to control their reasoning traces — even when explicitly told to. Longer, harder tasks amplify this effect, and larger models show only marginal improvement. Since models cannot easily conceal their reasoning, monitoring chain-of-thought may offer a reliable signal for detecting unsafe or deceptive behavior.',
    'https://openai.com/index/reasoning-models-chain-of-thought-controllability/'
  FROM new_newsletter
),

tool AS (
  INSERT INTO tools (newsletter_id, name, description, badge, try_link, read_link)
  SELECT
    id,
    'Agent Skills',
    'Anthropic introduces Agent Skills — modular capability packages that extend Claude with domain-specific knowledge. Skills are stored as structured folders and dynamically loaded when a task matches the skill description, letting Claude apply specialized workflows consistently rather than relying solely on general training. Think of them as pluggable playbooks for repeatable, expert-level tasks.',
    'Anthropic',
    'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview',
    'https://www.ainews.com/p/anthropic-introduces-built-in-evaluation-and-benchmarking-for-claude-agent-skills-to-improve-enterpr'
  FROM new_newsletter
),

ai AS (
  INSERT INTO model_releases (newsletter_id, title, description, badge, badge_class, link, sort_order)
  SELECT
    id,
    'Google launches Gemini 3.1 Flash-Lite',
    '• Built for High-Volume Workloads — Designed for large-scale developer workloads, delivering efficient performance for applications that require high throughput.• Cost-Efficient Model — $0.25 per 1M input tokens and $1.50 per 1M output tokens, providing strong performance while keeping operational costs low.• Fast and Low-Latency Performance — 2.5× faster Time to First Answer Token and 45% faster output speed, enabling responsive real-time applications.• Flexible Reasoning — Available in AI Studio and Vertex AI with adjustable thinking levels for translation, content moderation, UI generation, and more.',
    'Google',
    'blue',
    'https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-flash-lite/',
    1
  FROM new_newsletter
)

INSERT INTO interesting_links (newsletter_id, title, description, why, link, badge, badge_class, sort_order)
SELECT id, 'Google CLI + OpenClaw', 'Google released a new Workspace command-line tool that lets AI agents like OpenClaw access and automate tasks across Gmail, Drive, Docs, and other Workspace apps.', NULL, 'https://arstechnica.com/ai/2026/03/googles-new-command-line-tool-can-plug-openclaw-into-your-workspace-data/', 'Ars Technica', 'blue', 1 FROM new_newsletter
UNION ALL
SELECT id, 'SWE-Atlas', 'SWE-Atlas is a new benchmark from Scale AI that evaluates how well AI coding agents understand, test, and refactor real-world codebases.', NULL, 'https://scale.com/blog/swe-atlas', 'Scale AI', 'purple', 2 FROM new_newsletter
UNION ALL
SELECT id, 'Amazon AI Canvas Workspace', 'Amazon launched an AI Canvas workspace that turns seller data into interactive dashboards with real-time insights and recommended business actions.', NULL, 'https://www.ainews.com/p/amazon-launches-ai-canvas-workspace-to-turn-seller-data-into-real-time-business-decisions', 'Amazon', 'blue', 3 FROM new_newsletter;
